export const mockDatasets = [
  {
    id: 1,
    name: "ML Training data",
    description: "A comprehensive dataset about topic A.",
    price: "50",
  },
  {
    id: 2,
    name: "LLM Data",
    description: "In-depth analysis and data on topic B.",
    price: "75",
  },
  {
    id: 3,
    name: "LLAMA Dataset",
    description: "Dataset covering various aspects of topic C.",
    price: "100",
  },
  {
    id: 4,
    name: "Grok Dataset",
    description: "Dataset covering various aspects of topic C.",
    price: "10000",
  },
  {
    id: 5,
    name: "ChatGPT dataset",
    description: "Dataset covering various aspects of topic C.",
    price: "100",
  },
  {
    id: 6,
    name: "MNIST Training",
    description: "Dataset covering various aspects of topic C.",
    price: "100",
  },
  {
    id: 7,
    name: "Dogs and Cats Trainig",
    description: "Dataset covering various aspects of topic C.",
    price: "100250",
  },
  {
    id: 8,
    name: "Sugared Data",
    description: "Dataset covering various aspects of topic C.",
    price: "12300",
  },
  {
    id: 9,
    name: "Mr. Beast Stats",
    description: "A comprehensive dataset about topic A.",
    price: "50",
  },
  {
    id: 10,
    name: "Sports Data",
    description: "In-depth analysis and data on topic B.",
    price: "75",
  },
  {
    id: 11,
    name: "Copilot Dogfood",
    description: "Dataset covering various aspects of topic C.",
    price: "100",
  },
  {
    id: 12,
    name: "Dirty Practice Set",
    description: "Dataset covering various aspects of topic C.",
    price: "10000",
  },
  {
    id: 13,
    name: "Nautical Recent Data",
    description: "Dataset covering various aspects of topic C.",
    price: "100",
  },
  {
    id: 14,
    name: "MNIST Dirty Set",
    description: "Dataset covering various aspects of topic C.",
    price: "100",
  },
  {
    id: 15,
    name: "Video Games Dataset",
    description: "Dataset covering various aspects of topic C.",
    price: "100250",
  },
  {
    id: 16,
    name: "Marvel Heros Data",
    description: "Dataset covering various aspects of topic C.",
    price: "12300",
  },
];
